version: '3.7'

x-logging:
  &default-logging
  options:
    max-size: '1m'
    max-file: '1'
  driver: json-file

services:

  dash:
    container_name: dash
    build:
      context: ./
      dockerfile: ./ubi.Dockerfile
    logging: *default-logging
    volumes:
      - './app:/app'
    ports:
      - 8080:8080
    depends_on:
      - selenium

    # uncomment to run tests
    command: ["/wait-for-it.sh", "selenium:4444", "--", "pytest", "--remote-url", "http://selenium:4444"]

    # uncomment to get terminal
    # tty: true
    # command: ["bash"]

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome:88.0
    logging: *default-logging
    ports:
      - 4444:4444
      - 5900:5900
    shm_size: 2gb
